services:
  memos:
    image: neosmemo/memos:stable
    container_name: memos
    volumes:
      - memos:/var/opt/memos
    networks:
      - proxy_network
    ports:
      - 5230:5230
volumes:
  memos:
networks:
  proxy_network:
    name: proxy_network
    driver: bridge
