# on docker-server

services:
  dns-server:
    image: technitium/dns-server:14.3.0
    hostname: dns
    restart: unless-stopped
    ports:
      - "5381:5380/tcp" #DNS web console (HTTP)
      - "192.168.50.23:53:53/udp" # Local IP
      - "192.168.50.23:53:53/tcp" # Local IP
      - "100.125.190.103:53:53/udp" # Tailscale IP
      - "100.125.190.103:53:53/tcp" # Tailscale IP
    networks:
      - proxy_network
    environment:
      - DNS_SERVER_DOMAIN=dns.bluesaltlabs.com
    volumes:
      - config:/etc/dns
    sysctls:
      - net.ipv4.ip_local_port_range=1024 65535

volumes:
  config:

networks:
  proxy_network:
    driver: bridge
