services:
  app:
    container_name: monica
    image: monicahq/monica:5.0-fpm-alpine
    environment:
      - APP_KEY=${APP_KEY}
      - DB_PASSWORD=${DB_PASSWORD}
      - MEILISEARCH_KEY=${MEILISEARCH_KEY}
    volumes:
      - data:/var/www/html/storage
    networks:
      - monica
    restart: always
    depends_on:
      - db
      - redis
      - memcached
      - meilisearch

  db:
    image: mariadb:11
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=monica
      - MYSQL_USER=monica
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - monica
    restart: always

  redis:
    image: redis:alpine
    restart: always
    networks:
      - monica

  cron:
    image: monicahq/monica:apache
    command: cron.sh
    environment:
      - APP_KEY=${APP_KEY}
      - DB_PASSWORD=${DB_PASSWORD}
      - MEILISEARCH_KEY=${MEILISEARCH_KEY}
    volumes:
      - data:/var/www/html/storage
    networks:
      - monica
    restart: always

  memcached:
    image: memcached:alpine
    networks:
      - monica

  meilisearch:
    image: getmeili/meilisearch:latest
    environment:
      - MEILI_MASTER_KEY=${MEILISEARCH_KEY}
      - MEILISEARCH_NO_ANALYTICS=true
    volumes:
      - meili_data:/meili_data
    networks:
      - monica

  web:
    image: monicahq/monica:apache
    ports:
      - 80:80
    volumes:
      - data:/var/www/html/storage:ro
    networks:
      - monica
    restart: always
    depends_on:
      - app

volumes:
  data:
  mysqldata:
  meili_data:

networks:
  monica:
  proxy_network:
    external: true
