services:
  tududi:
    image: chrisvel/tududi:latest
    container_name: tududi
    restart: unless-stopped
    environment:
      - TUDUDI_USER_EMAIL=lukerz8@gmail.com
      - TUDUDI_USER_PASSWORD=password
      - TUDUDI_SESSION_SECRET=${TUDUDI_SESSION_SECRET:-$(openssl rand -hex 64)}
    volumes:
      - tududi_db:/app/backend/db
      - tududi_uploads:/app/backend/uploads
    networks:
      - proxy_network
    ports:
      - 3002:3002
volumes:
  tududi_db:
  tududi_uploads:
networks:
  proxy_network:
    name: proxy_network
    driver: bridge
