services:
  writefreely:
    build:
      context: .
      args:
        - REPOSITORY=https://github.com/writefreely/writefreely.git
        - VERSION=${VERSION:-0.15.1}
    restart: unless-stopped
    ports:
      - $PORT:8080
    networks:
      - proxy_network
    environment:
      - USERNAME
      - PASSWORD
    volumes:
      - writefreely_config:/config:Z
      - writefreely_data:/data:Z
volumes:
  writefreely_config:
    driver: local
  writefreely_data:
    driver: local
networks:
  proxy_network:
    name: proxy_network
    driver: bridge
