services:
  tailscale:
    image: tailscale/tailscale:latest
    container_name: tailscale.docker-server
    hostname: tailscale.docker-server
    environment:
      - TS_AUTHKEY=$TS_AUTHKEY
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    volumes:
      - tailscale_data:/var/lib
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
    restart: unless-stopped
  nginx:
    image: nginx
    network_mode: service:tailscale
    restart: unless-stopped
volumes:
  tailscale_data:
    external: true
