services:
  linkding:
    container_name: "${LD_CONTAINER_NAME:-linkding}"
    image: sissbruecker/linkding:latest
    ports:
      - "${LD_HOST_PORT:-9090}:9090"
    volumes:
      - "${LD_HOST_DATA_DIR:-data}:/etc/linkding/data"
    networks:
      - proxy_network
    restart: unless-stopped
volumes:
  data:
networks:
  proxy_network:
    name: proxy_network
    driver: bridge
